### PR TITLE
Update quick-start.md with minor improvements

### PR DESCRIPTION
**Pull request by oscr**
Some minor improvements for quick start that where suggested in the previous pr #10 

@matskiv Regarding the NodePort feedback I didn't get that running. Maybe I misunderstood how it works. But any suggestion or update pr is welcome. 

As a side note: I noticed vlcuster isn't added to the https://cluster-api.sigs.k8s.io/user/quick-start.html yet. Maybe worth considering given how well it works to get started with?

### CODE REVIEW

**Comment by matskiv** [comment]
Thank you for the PR. Improvements look good. :+1: 

> Regarding the NodePort feedback I didn't get that running. Maybe I misunderstood how it works. But any suggestion or update pr is welcome.
The NodePort service is useful for easy `vcluster connect` when a local cluster is used. The vcluster cli should detect this scenario and depending on the type of local cluster it would create vcluster kube context that will work without port forwarding, e.g. by deploying a proxy container in docker.
If you are interested in getting to the bottom of it - please use vcluster cli v0.10.0+ and let me know what is the output of `vcluster connect kind -n vcluster --debug` when you set helm values var to the following when creating a cluster:
```
export HELM_VALUES="service:\n  type: NodePort"
```

You should see something like this:
```
$ vcluster connect vcluster -n vcluster
info   Starting proxy container...
done √ Switched active kube context to vcluster_kind_vcluster_kind
- Use `vcluster disconnect` to return to your previous kube context
- Use `kubectl get namespaces` to access the vcluster
$ 
```

**Comment by matskiv** [comment]
> As a side note: I noticed vlcuster isn't added to the https://cluster-api.sigs.k8s.io/user/quick-start.html yet. Maybe worth considering given how well it works to get started with?

Oh, this is a really good idea! I created a tracking issue to do this - #12

**Comment by oscr** [comment]
> ```
> export HELM_VALUES="service:\n  type: NodePort"
> ```

Thank you for this advice! It was a great addition. I've added it to this pr.

**Review by matskiv — APPROVED** [review]
Thank you for your contribution!
The update looks great.

**Pull request merged**
